apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rubygems-releaser
  description: "Reusable GitHub Actions workflows for publishing public gems to RubyGems.org via trusted publishing, using Release Please for versioning and changelogs"
  tags:
    - github-actions
spec:
  type: library
  lifecycle: stable
  owner: CODEOWNERS
