name: Release Gem to RubyGems.org

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'The directory containing the gem (for monorepos with gems in subdirectories). Defaults to repository root.'
        required: false
        type: string
        default: '.'

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release-please
